remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: '4dinha'
description: 'ğŸƒ Um jogo de truco, estratÃ©gia e zoeira onde a sorte e a malandragem decidem o destino dos jogadores! ğŸ”¥ Aposte, blefe e dispute atÃ© o Ãºltimo truco â€“ mas cuidado, porque aqui quem vacila, danÃ§a! ğŸ˜ˆ SerÃ¡ que vocÃª tem o que Ã© preciso para ser o rei da mesa? ğŸ‘‘'
show_downloads: false
google_analytics: '' # Adicione seu Google Analytics ID se necessÃ¡rio
